### PR TITLE
Second milestone completed

### PR DESCRIPTION
**Pull request by xtrmdarc**
We kindly request a code review for our second milestone of the final project of the app 'stay in touch'. We have implemented the following features:
- A user can send a friendship invitation to another user
- A user can accept or reject an invitation from another user
- Users can only see theirs and their friends' posts in the timeline
- A user can see friendship invitations sent from other users

We also created the appropriate test cases using the rail's native testing suite. Please, **use rails test** to run the test cases.

As a side note, we decided to use the status attribute as an integer because we wanted to manage multiple friendship status states like accepted, rejected and sent in further development on our own.

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello @xtrmdarc @bren2102 ,
The milestone is OK except a few things

1. You are supposed to use Postgres as Database not SQLite

2. Please, as indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png), you should add integration tests.
Please, they must be writen using RSpec

Kindly make the changes and submit a new code review requests
Thanks

Mael FOSSO

**Comment by xtrmdarc** [comment]
Hi!
Thanks so much for your review. We added PostgreSQL as a database so we can deploy it to Heroku.
image

Also, we added integration and unit tests for the friendship relations :
image

Please let us know if we are missing something.

**Review by wathigo — CHANGES_REQUESTED** [review]
### Changes Required
Hello team :wave: 
Great work with the database configuration.
As mentioned by @maelfosso, unit and integration tests should be done using [rspec-rails](https://github.com/rspec/rspec-rails) and [capybara](https://github.com/teamcapybara/capybara).

**After implementing the changes, submit another request for review!** 

**All the best :four_leaf_clover: 
Simon Wathigo**

**Comment by xtrmdarc** [comment]
Hi!

Thanks for your valuable feedback. **We successfully created the unit tests using rspec and the integrations tests using capybara as suggested in the last review. We have completely and only tested the features related to the friendship functionality** as stated in the project specifications. 
**rspec**

image

**capybara**

image

Thanks for the review.

**Review by fatymahmed — APPROVED** [review]
### Hi @xtrmdarc @bren2102,
### Great job making the suggested changes🎉🎉

### It's a 👍🏾 from me!
## ✔️ Approved!

Good luck with your next projects.

**Pull request merged**
